#!/bin/bash

set -e

if [ ! -d "sources/poky" ]; then
   echo "Fetching poky sources ..."
   git clone git://git.yoctoproject.org/poky -b hardknott sources/poky
fi

if [ ! -d "sources/meta-openembedded" ]; then
   echo "Fetching openembedded sources ..."
   git clone git://git.openembedded.org/meta-openembedded -b hardknott sources/meta-openembedded
fi

if [ ! -d "sources/meta-raspberrypi" ]; then
   echo "Fetching raspberrypi sources ..."
   git clone git://git.yoctoproject.org/meta-raspberrypi -b hardknott sources/meta-raspberrypi
fi

# We'd like to have our custom local conf
export TEMPLATECONF=`pwd`/sources/meta-aurora/build/conf
. sources/poky/oe-init-build-env

echo -e "#######################################"
echo -e "# To initialize the environment, run: #"
echo -e "#    . sources/poky/oe-init-build-env #"
echo -e "#                                     #"
echo -e "# To build the image, run:            #"
echo -e "#    bitbake aurora                   #"
echo -e "#######################################"
